name: Go & Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # -------- GO --------
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Run Go tests
        run: go test -v ./...

      # -------- PYTHON --------
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14.1'
          
      - name: Install Python dependencies
        run: pip install sortedcontainers

      - name: Run Python script-based tests
        shell: bash
        run: |
          set -e
          for test in $(find . -name "test_*.py"); do
            echo "Running $test"
            python -B "$test"
          done

